<?php
$escape = $this->plugin('escapeHtml');
$resourceTemplate = $item->resourceTemplate();
$resourceTemplateLabel = ($resourceTemplate) ? $resourceTemplate->label() : '';
$this->htmlElement('body')->appendAttribute('class', 'item resource show ' . lcfirst($resourceTemplateLabel));
$embedMedia = $this->siteSetting('item_media_embed', false);
$itemMedia = $item->media();
$imageMedia = [];
$otherMedia = [];
$whitelist = ['image/bmp', 'image/gif', 'image/jpeg', 'image/png', 'image/svg+xml'];
foreach ($itemMedia as $media) {
    $mediaType = $media->mediaType();
    $mediaRenderer = $media->renderer();
    if (in_array($mediaType, $whitelist) || (strpos($mediaRenderer, 'youtube') !== false)) {
        $imageMedia[] = $media;
    } else {
        $otherMedia[] = $media;
    }
}
?>

<?php if ($embedMedia && $itemMedia): ?>
    <?php if ($resourceTemplate && ($resourceTemplate->label() == 'Recording')): ?>
    <div class="audio media-embeds">
      <?php foreach ($otherMedia as $media): ?>
      <?php echo $media->render(); ?>
      <?php endforeach; ?>
    </div>
    <?php else: ?>
    <?php endif; ?>
    <div class="media-embeds">
    <?php foreach ($imageMedia as $media): ?>
        <?php echo $media->render(); ?>
    <?php endforeach; ?>
    </div>
<?php endif; ?>
<div class="item-head">
<?php echo $this->pageTitle($item->displayTitle(), 2); ?>
<?php echo ($itemRole = $item->value('dcterms:type')) ? '<span class="role">' . $itemRole . '</span>': ''; ?>
</div>

<?php $this->trigger('view.show.before'); ?>
<div class="item-metadata"><?php echo $item->displayValues(); ?></div>
<?php if ($itemDescription = $item->value('dcterms:description')): ?>
<div class="item-description"><?php echo $itemDescription->asHtml(); ?></div>
<?php endif; ?>
<?php if (!$embedMedia && $itemMedia): ?>
<div class="media-list">
    <?php foreach ($itemMedia as $media): ?>
        <?php echo $media->linkPretty(); ?>
    <?php endforeach; ?>
</div>
<?php endif; ?>
<?php
$page = $this->params()->fromQuery('page', 1);
$property = $this->params()->fromQuery('property');
$subjectValues = $item->displaySubjectValues($page, 25, $property);
?>
<?php if ($subjectValues): ?>
<div id="item-linked">
    <h3>Related to <?php echo $item->displayTitle(); ?></h3>
    <?php echo $subjectValues; ?>
</div>
<?php endif; ?>

<?php $this->trigger('view.show.after'); ?>
