<?php
$escape = $this->plugin('escapeHtml');
$resourceTemplate = $item->resourceTemplate();
$resourceTemplateLabel = ($resourceTemplate) ? $resourceTemplate->label() : '';
$this->htmlElement('body')->appendAttribute('class', 'item resource show ' . lcfirst($resourceTemplateLabel));
$embedMedia = $this->siteSetting('item_media_embed', false);
$itemMedia = $item->media();
?>

<?php if ($embedMedia && $itemMedia): ?>
    <?php if ($resourceTemplate && ($resourceTemplate->label() == 'Recording')): ?>
    <div class="audio media-embeds">
    <?php else: ?>
    <div class="media-embeds">
    <?php endif; ?>
    <?php foreach ($itemMedia as $media):
        echo $media->render();
    endforeach;
    ?>
    </div>
<?php endif; ?>
<div class="item-head">
<?php echo $this->pageTitle($item->displayTitle(), 2); ?>
<?php echo ($itemRole = $item->value('dcterms:type')) ? '<span class="role">' . $itemRole . '</span>': ''; ?>
</div>

<?php $this->trigger('view.show.before'); ?>
<div class="item-metadata"><?php echo $item->displayValues(); ?></div>
<?php echo ($itemDescription = '<div class="item-description">' . $item->value('dcterms:description') . '</div>') ? $itemDescription : ''; ?>
<?php if (!$embedMedia && $itemMedia): ?>
<div class="media-list">
    <?php foreach ($itemMedia as $media): ?>
        <?php echo $media->linkPretty(); ?>
    <?php endforeach; ?>
</div>
<?php endif; ?>
<?php
$page = $this->params()->fromQuery('page', 1);
$property = $this->params()->fromQuery('property');
$subjectValues = $item->displaySubjectValues($page, 25, $property);
?>
<?php if ($subjectValues): ?>
<div id="item-linked">
    <h3>Related to <?php echo $item->displayTitle(); ?></h3>
    <?php echo $subjectValues; ?>
</div>
<?php endif; ?>

<?php $this->trigger('view.show.after'); ?>
