<div class="preview-block">

<?php if ($this->heading): ?>
<h2><?php echo $this->heading; ?></h2>
<?php endif; ?>

<ul class="resource-list preview">
<?php
$headingTerm = $this->siteSetting('browse_heading_property_term', 'dcterms:title');
$bodyTerm = $this->siteSetting('browse_body_property_term', 'dcterms:description');
foreach ($this->resources as $item):
    $heading = $item->value($headingTerm, ['default' => $this->translate('[Untitled]')]);
    $genres = $item->value('dcterms:subject', ['all' => true]);
?>
    <li class="item resource">
        <h4><?php echo $item->linkPretty('medium'); ?></h4>
        <?php if (count($genres) > 0): ?>
            <ul class="genres">
            <?php foreach ($genres as $genre): ?>
                <li><?php echo $genre->asHtml(); ?></li>
            <?php endforeach; ?>
            </ul>
        <?php endif; ?>
    </li>
<?php endforeach; ?>
</ul>

<?php
$linkText = $this->linkText == '' ? $this->translate('Browse all') : $this->linkText;
echo $this->hyperlink($linkText, $this->url(
    'site/resource', ['controller' => 'item', 'action' => 'browse'], ['query' => $this->query], true
));
?>

</div>
