<?php
$this->headLink()->appendStylesheet($this->assetUrl('css/site/page.css', 'FacetedBrowse'));
$this->headScript()->appendFile($this->assetUrl('js/faceted-browse.js', 'FacetedBrowse'));
$this->headScript()->appendFile($this->assetUrl('js/site/page.js', 'FacetedBrowse'));
$this->facetedBrowse()->prepareFacets();

$this->htmlElement('body')->appendAttribute('class', 'faceted-browse-page resource browse');
$this->pageTitle($page->title(), 2);

$categories = $page->categories();
$categoryId = null;
$categoryQuery = null;
if (1 === count($categories)) {
    $category = current($categories);
    $categoryId = $category->id();
    $categoryQuery = $category->query();
}
?>
<div class="assets hero-image-spins default">
    <img src="banner url">
</div>
<div class="div-banner" style="margin-top: -40px;">
    <div class="spin-icon"><img draggable="false" src="https://hearingtheamericas.org/files/asset/8eef2f04b3d1947e604dbf75c0d4d0dc1e777983.png" /></div>
    <div class="spin-banner">
        <h2>Browse Artists</h2>
    </div>
</div>
<div id="container" 
    data-url-categories="<?php echo $this->escapeHtml($this->url(null, ['action' => 'categories'], true)); ?>"
    data-url-facets="<?php echo $this->escapeHtml($this->url(null, ['action' => 'facets'], true)); ?>"
    data-url-browse="<?php echo $this->escapeHtml($this->url(null, ['action' => 'browse'], true)); ?>"
    data-category-id="<?php echo $this->escapeHtml($categoryId); ?>"
    data-category-query="<?php echo $this->escapeHtml($categoryQuery); ?>">
    <div id="section-sidebar"></div>
    <div id="section-content"></div>
</div>
